version: 3
updates:
  # js.foresight package
  - package-ecosystem: "npm"
    directory: "/packages/js.foresight"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5

  # js.foresight-devtools package
  - package-ecosystem: "npm"
    directory: "/packages/js.foresight-devtools"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
